name: dependabot-pr
on:
  workflow_run:
    workflows: ["build-pr"]
    types:
      - completed
jobs:
  autoapprove:
    name: Approve pull request
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
          github.event.workflow_run.conclusion == 'success' &&
          github.actor == 'dependabot[bot]' }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter(artifact => artifact.name == "pr")[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });

            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));

      - run: unzip pr.zip

      - name: Approve and Merge PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var pr_number = Number(fs.readFileSync('./number'));

            core.debug(`Creating APPROVE review for pull request #${pr_number}`)
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              event: "APPROVE"
            })
            core.debug(`Approved pull request #${pr_number}`)

            core.debug(`Merging pull request #${pr_number}`)
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
               pull_number: pr_number,
            })
            core.debug(`Merged pull request #${pr_number}`)
