name: dependabot-pr
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install and build
      run: |
        yarn install
        yarn run coverage
        yarn run build
      env:
        CI: true

  autoapprove:
    name: Approve pull request
    runs-on: ubuntu-latest
    needs: build
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
      - name: Approve
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { pull_request: pr, repository: repo } = context.payload

            core.debug(`Creating APPROVE review for pull request #${pr.number}`)
            await github.pulls.createReview({
              owner: repo.owner.login,
              repo: repo.name,
              pull_number: pr.number,
              event: "APPROVE"
            })
            core.debug(`Approved pull request #${pr.number}`)

  automerge:
    name: Merge pull request
    runs-on: ubuntu-latest
    needs: autoapprove
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
      - name: Merge
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { pull_request: pr, repository: repo } = context.payload

            core.debug(`Merging pull request #${pr.number}`)
            await github.pulls.merge({
              owner: repo.owner.login,
              repo: repo.name,
              pull_number: pr.number
            })
            core.debug(`Merged pull request #${pr.number}`)
