name: dependabot-pr
on:
  workflow_run:
    workflows: ["build-pr", "lint-pr"]
    types:
      - completed
jobs:
  autoapprove:
    name: Approve pull request
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
          github.event.workflow_run.conclusion == 'success' &&
          github.actor == 'dependabot[bot]' }}
    steps:
      - name: Approve
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { pull_request: pr, repository: repo } = context.payload

            core.debug(`Creating APPROVE review for pull request #${pr.number}`)
            await github.pulls.createReview({
              owner: repo.owner.login,
              repo: repo.name,
              pull_number: pr.number,
              event: "APPROVE"
            })
            core.debug(`Approved pull request #${pr.number}`)

  # Handled by GitHub's auto-merge feature
  #
  # automerge:
  #   name: Merge pull request
  #   runs-on: ubuntu-latest
  #   needs: autoapprove
  #   if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
  #   steps:
  #     - name: Merge
  #       uses: actions/github-script@v2
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         script: |
  #           const { pull_request: pr, repository: repo } = context.payload

  #           core.debug(`Merging pull request #${pr.number}`)
  #           await github.pulls.merge({
  #             owner: repo.owner.login,
  #             repo: repo.name,
  #             pull_number: pr.number
  #           })
  #           core.debug(`Merged pull request #${pr.number}`)
